apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synthetic-monitoring-agent.fullname" . }}
  labels:
    {{- include "synthetic-monitoring-agent.labels" . | nindent 4 }}
spec:
  minReadySeconds: 10
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "synthetic-monitoring-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synthetic-monitoring-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - args:
            - /usr/local/bin/synthetic-monitoring-agent
            - -api-server-address $(API_SERVER)
            - -api-token $(API_TOKEN)
            {{- if .Values.agent.debug }}
            - -debug
            {{- else if .Values.agent.verbose }}
            - -verbose
            {{- end }}
          command:
            - sh
            - -c
          env:
            - name: API_SERVER
              value: {{ .Values.agent.apiServerAddress | quote }}
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: api-token
                  name: {{ include "synthetic-monitoring-agent.fullname" . }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4050
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
