---
loki:
  serviceName: ""  # Defaults to "${RELEASE}-loki" if not set
  servicePort: 3100
  serviceScheme: http
  servicePath: /api/prom/push
  # user: user
  # password: pass
config:
  port: 2020
  tenantID: '""'
  batchWait: 1
  batchSize: 1048576
  loglevel: warn
  lineFormat: json
  k8sLoggingExclude: "Off"
  k8sLoggingParser: "Off"
  memBufLimit: "5MB"
  removeKeys:
    - kubernetes
    - stream
  autoKubernetesLabels: false
  labels: '{job="fluent-bit"}'
  labelMap:
    kubernetes:
      namespace_name: namespace
      labels:
        app: app
        release: release
      host: node
      container_name: container
      pod_name: instance
    stream: stream
#  Custom inputs
#  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
#      [INPUT]
#          Name tail
#          Path /var/log/containers/*.log
#          Parser docker
#          Tag custom.*
#          Mem_Buf_Limit 5MB
#          Skip_Long_Lines On
#      [INPUT]
#          Name systemd
#          Tag host.*
#          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
#          Read_From_Tail On
#  Custom filters
#  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
#      [FILTER]
#          Name geoip2
#          Match netty.accessLog
#          Database /opt/geoip/GeoLite2-City.mmdb
#          Lookup_key ip.remoteAddress
#          Record ip.country     ip.remoteAddress %{country.names.en}
#          Record ip.countryIso  ip.remoteAddress %{country.iso_code}
#          Record ip.city        ip.remoteAddress %{city.names.en}
#          Record ip.latitude    ip.remoteAddress %{location.latitude}
#          Record ip.longitude   ip.remoteAddress %{location.longitude}
#  Custom outputs
#  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
#      [OUTPUT]
#          Name es
#          Match kube.*
#          Host elasticsearch-master
#          Logstash_Format On
#          Retry_Limit False
#      [OUTPUT]
#          Name es
#          Match host.*
#          Host elasticsearch-master
#          Logstash_Format On
#          Logstash_Prefix node
#          Retry_Limit False
#  Custom parsers
#  ## https://docs.fluentbit.io/manual/pipeline/parsers
  parsers: |
#      [PARSER]
#          Name json_no_time
#          Format json
#          Time_Keep Off

affinity: {}

annotations: {}

deploymentStrategy: RollingUpdate

image:
  repository: grafana/fluent-bit-plugin-loki
  tag: 2.1.0-amd64
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be present in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  # pullSecrets:
  #   - myRegistrKeySecretName

nameOverride: fluent-bit-loki

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

## Pod Labels
podLabels: {}

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "2020"
  prometheus.io/path: /api/v1/metrics/prometheus

## Assign a PriorityClassName to pods if set
# priorityClassName:

rbac:
  create: true
  pspEnabled: true

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

serviceAccount:
  create: true
  name:

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations:
- key: node-role.kubernetes.io/master
  effect: NoSchedule

# Extra volumes to scrape logs from
volumes:
- name: varlog
  hostPath:
    path: /var/log
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers

volumeMounts:
- name: varlog
  mountPath: /var/log
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true

serviceMonitor:
  enabled: false
  interval: ""
  additionalLabels: {}
  annotations: {}
  # scrapeTimeout: 10s
